name: 'Backup from Cloud MongoDB Atlas'
description: 'Backup from Cloud MongoDB Atlas'
author: 'JimCat'

inputs:
  mongodb_uri:
    description: 'Cloud MongoDB Server URI'
    required: true
outputs:
  mongodb_uri:
    description: 'Cloud MongoDB Server URI'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mongodb_uri }}
branding:
  icon: 'database'
  color: 'gray-dark'